language: python

cache:
  pip: true

python:
  - "3.5"

install:
  - pip install -r requirements.txt

env:
  global:
    - DJANGO_SETTINGS_MODULE="tutory_api.settings.settings"

script:
  - bash run_tests.sh

git:
  depth: 10

branches:
  only:
    - master
    - dev

notifications:
  email:
    on_success: change
    on_failure: always
