# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_major_mid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
    ]
