# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_auto_20170808_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_outlet', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('IG', 'Instagram'), ('RE', 'Reddit')], default='FB', max_length=2)),
                ('comment_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('FO', 'Football'), ('SO', 'Soccer'), ('BA', 'Baseball'), ('HO', 'Hockey'), ('TE', 'Tennis'), ('BS', 'Basketball')], default='FO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('FO', 'Football'), ('SO', 'Soccer'), ('BA', 'Baseball'), ('HO', 'Hockey'), ('TE', 'Tennis'), ('BS', 'Basketball')], default='FO', max_length=2)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Team'),
        ),
        migrations.AddField(
            model_name='comment',
            name='team_to_win',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Team'),
        ),
    ]
