# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20170812_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='teams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='common.Team'),
        ),
    ]
