# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20170813_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateField(default='1997-06-06'),
        ),
    ]
