# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='team_to_win',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Team'),
        ),
    ]
