# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20170813_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.CharField(default='nfl', max_length=10),
        ),
    ]
