# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_comment_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
